# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aias-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SVProgressHUD'
  pod 'ReusableKit' 
  pod 'ReusableKit/RxSwift'
  pod 'PinLayout'
  pod 'RxAlamofire'
  pod 'KeychainAccess'
  # Pods for aias-iOS

  target 'aias-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aias-iOSUITests' do
    # Pods for testing
  end

end
